language: php

env:
  - APP_ENV=travis
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - composer self-update
  - composer require phpunit/phpunit
  - composer install --prefer-source --no-interaction --dev
script: 
    - phpunit 
