language: php

env:
  - APP_ENV=travis
php:
  - 5.6
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - composer require "phpunit/phpunit" "4.8.*"
  - composer install --prefer-source --no-interaction --dev
script: 
    - phpunit 
