language: php

env:
  - APP_ENV=travis
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - ./tests/install.sh

before_script:
  - composer self-update
  - composer require "phpunit/phpunit" "4.8.*"
  - composer update
  - cd bin && ./Server.php &

script: 
    - phpunit --configuration "tests/configuration.xml" --coverage-text 
