language: php

env:
  - APP_ENV=travis
php:
  - 5.6
  - hhvm

install:
  - ./install.sh
before_script:
  - composer require "phpunit/phpunit" "4.8.*"
  - composer install
script: 
    - phpunit --configuration phpunit.xml.dist --coverage-text 
